routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('login');
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware'=>['admin']], function (){
	Route::get('/consultar', function () {
    return view('consultar');
	});
	Route::get('/insertar', function () {
	    return view('insertar');
	});
	Route::get('/reportes', function () {
	    return view('reportes');
	});
	Route::resource('alumnos', 'alumnosController');
	Route::resource('aula', 'aulaController');
	Route::resource('profesores', 'profesoresController');
	Route::resource('inscripcion', 'inscripcionesController');
	Route::post('nota/store',[
		'uses' => 'notasController@store',
		 'as'  => 'nota.store'
	]);
	Route::get('nota/{id}/consultar',[
		'uses' => 'notasController@consultar',
		 'as'  => 'nota.consultar'
	]);
	Route::get('notas/index',[
		'uses' => 'notasController@index',
		 'as'  => 'notas'
	]);
	Route::resource('notas', 'notasController');
	Route::get('cuentas/create',[
		'uses' => 'HomeController@create',
		 'as'  => 'cuentas.create'
	]);
	Route::post('cuentas/store',[
		'uses' => 'HomeController@store',
		 'as'  => 'cuentas.store'
	]);
	Route::resource('representantes', 'representantesController');
	Route::get('representante/create/{cedula}', [
		'uses'	=> 'representantesController@create',
		'as'	=> 'representante.create'
	]);
	  Route::post('profesores/cedula', [
		'uses'	=> 'profesoresController@cedula',
		'as'	=> 'profesores.cedula'
	]);
	Route::get('alumno/validar/{cedula}', [
		'uses'	=> 'alumnosController@validar',
		'as'	=> 'alumno.validar'
	]);
  Route::get('alumno/getalumno/{id}', [
    'uses'	=> 'alumnosController@getAlumno',
    'as'	=> 'alumno.getAlumno'
  ]);

    Route::get('alumnospdf', function(){
    	$items = App\Alumno::all();
    	$pdf = PDF::loadView('reportepdf.alumnopdf', ['items' => $items]);
    	return $pdf->stream('alumnos.pdf');
    });
    Route::get('profesorespdf', function(){
    	$items = App\Profesor::all();
    	$pdf = PDF::loadView('reportepdf.profesorpdf', ['items' => $items]);
    	return $pdf->stream('profesores.pdf');
    });
    Route::get('representantespdf', function(){
    	$items = App\Representante::all();
    	$pdf = PDF::loadView('reportepdf.representantepdf', ['items' => $items]);
    	return $pdf->stream('representantes.pdf');
    });
    Route::get('inscripcionespdf', function(){
    	$items = App\Alumno::all();
    	$pdf = PDF::loadView('reportepdf.inscripcionpdf', ['items' => $items]);
    	return $pdf->stream('inscripciones.pdf');
    });

    Route::get('repalumnospdf/{id}/',[
		'uses' => 'alumnosController@reporte',
		 'as'  => 'reportealumnos'
	]);

    Route::post('validarcedula',[
		'uses' => 'representantesController@validar',
		 'as'  => 'validarcedula'
	]);

});

app/Profesor.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Profesor extends Model
{
    protected $table = 'profesor';
    
    protected $fillable = [
        'nombre',
    	'apellidos',
    	'cedula',
    	'telefono',
    	'correo',
    	'direccion',
        'aula',
        'turno',
        ];
}

resources/views/consultar/profesor/edit.blade.php
@extends('layouts.app')

@section('content')
    <div id="content-header">
    <div id="breadcrumb"> <a href="index.html" title="Go to Home" class="tip-bottom"><i class="icon-home"></i> Insertar </a> <a href="#" class="tip-bottom">Profesor</a> <a href="#" class="current"></div>
  </div>


<div class="span10">
 <div class="widget-box">
        <div class="widget-title"> <span class="icon"> <i class="icon-align-justify"></i> </span>
          <h5>Información del profesor(a)</h5>
        </div>
        <div class="widget-content nopadding">
      
          {!!Form::model($item, ['route'=>['profesores.update', $item->id], 'method'=>'PUT', 'class'=>'form-horizontal'])!!}
            <div class="control-group">
              <label class="control-label">Nombres:</label>
              <div class="controls">
                {!!Form::text('nombre', null,['class'=>'span7'])!!}
              </div>
            </div>
            <div class="control-group">
              <label class="control-label">Apellidos:</label>
              <div class="controls">
                {!!Form::text('apellidos', null,['class'=>'span7'])!!}
              </div>
            </div>
            <div class="control-group">
              <label class="control-label">Cedula:</label>
              <div class="controls">
                {!!Form::text('cedula', null,['class'=>'span7'])!!}
              </div>
            </div>
            <div class="control-group">
              <label class="control-label">Dirección:</label>
              <div class="controls">
                {!!Form::text('direccion', null,['class'=>'span7'])!!}
              </div>
            </div>
             <div class="control-group">
              <label class="control-label">Teléfono:</label>
              <div class="controls">
                {!!Form::text('telefono', null,['class'=>'span7'])!!}
              </div>
            </div>
            <div class="control-group">
              <label class="control-label">Correo</label>
              <div class="controls">
                {!!Form::text('correo', null,['class'=>'span7'])!!}
              </div>
            </div>
            <div class="control-group">
              <label class="control-label">Aula</label>
              <div class="controls">
                {!!Form::select('aula', ['1' => 'Aula 1', '2' => 'Aula 2', '3' => 'Aula 3', '4' => 'Aula 4', '5' => 'Aula 5', '6' => 'Aula 6', '7' => 'Aula 7', '8' => 'Aula 8', '9' => 'Aula 9', '10' => 'Aula 10'])!!}
              </div>
            </div>
            <div class="control-group">
              <label class="control-label">Turno</label>
              <div class="controls">
                {!!Form::select('turno', ['Mañana' => 'Mañana', 'Tarde' => 'Tarde'])!!}
              </div>
            </div>
            <div class="form-actions">
              <button type="submit" class="btn btn-success">Aceptar</button>
            </div>
          {!!Form::close()!!}
          </div>
        </div>
</div>



<!--Footer-part-->

<div class="row-fluid">
  <div id="footer" class="span12"> 2018 &copy; Unidad Educativa Simoncito "Las Americas" <a href="http://themedesigner.in"> - Desarrollado por: Francisco La Rosa</a> </div>
</div>

@endsection

resources/views/consultar/profesor/index.blade.php
@extends('layouts.app')

@section('content')
    <div id="content-header">
    <div id="breadcrumb"> <a href="index.html" title="Go to Home" class="tip-bottom"><i class="icon-home"></i> Consultar</a> <a href="#" class="tip-bottom">Profesor</a> <a href="#" class="current"></div>
  </div>


<div class="span10">

        <div class="widget-box">
          <div class="widget-title"> <span class="icon"> <i class="icon-th"></i> </span>
            <h5>Consultar Profesores</h5>
          </div>
          <div class="widget-content nopadding">
            <table class="table table-bordered table-striped">
              <thead>
                <tr>
                  <th>ID</th>
                  <th>Nombre </th>
                  <th>Apellidos </th>
                  <th>Cedula</th>
                  <th>Telefono</th>
                  <th>Correo</th>
                  <th>Dirección</th>
                   <th>Aula</th>
                  <th>Turno</th>
                  <th>Opciones</th>
                </tr>
              </thead>
              <tbody>
                 @foreach($items as $item)
                  <tr class="odd gradeX">
                    <td>{{$item->id}}</td>
                    <td>{{$item->nombre}}</td>
                    <td>{{$item->apellidos}}</td>
                    <td>{{$item->cedula}}</td>
                    <td>{{$item->telefono}}</td>
                    <td>{{$item->correo}}</td>
                    <td>{{$item->direccion}}</td>
                    <td>{{$item->aula}}</td>
                    <td>{{$item->turno}}</td>
                    <td >  <center> <a href="{{route('profesores.edit', $item->id)}}" class="btn btn-mini btn-warning">Modificar</a></center></td>
                  </tr>
                 @endforeach
              </tbody>
            </table>
          </div>
        </div>
        
</div>
@endsection