routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('login');
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware'=>['admin']], function (){
	Route::get('/consultar', function () {
    return view('consultar');
	});
	Route::get('/insertar', function () {
	    return view('insertar');
	});
	Route::get('/reportes', function () {
	    return view('reportes');
	});
	Route::resource('alumnos', 'alumnosController');
	Route::resource('aula', 'aulaController');
	Route::resource('profesores', 'profesoresController');
	Route::resource('inscripcion', 'inscripcionesController');
	Route::post('nota/store',[
		'uses' => 'notasController@store',
		 'as'  => 'nota.store'
	]);
	Route::get('nota/{id}/consultar',[
		'uses' => 'notasController@consultar',
		 'as'  => 'nota.consultar'
	]);
	Route::get('notas/index',[
		'uses' => 'notasController@index',
		 'as'  => 'notas'
	]);
	Route::resource('notas', 'notasController');
	Route::get('cuentas/create',[
		'uses' => 'HomeController@create',
		 'as'  => 'cuentas.create'
	]);
	Route::post('cuentas/store',[
		'uses' => 'HomeController@store',
		 'as'  => 'cuentas.store'
	]);
	Route::resource('representantes', 'representantesController');
	Route::get('representante/create/{cedula}', [
		'uses'	=> 'representantesController@create',
		'as'	=> 'representante.create'
	]);
	  Route::post('profesores/cedula', [
		'uses'	=> 'profesoresController@cedula',
		'as'	=> 'profesores.cedula'
	]);
	Route::get('alumno/validar/{cedula}', [
		'uses'	=> 'alumnosController@validar',
		'as'	=> 'alumno.validar'
	]);
  Route::get('alumno/getalumno/{id}', [
    'uses'	=> 'alumnosController@getAlumno',
    'as'	=> 'alumno.getAlumno'
  ]);

    Route::get('alumnospdf', function(){
    	$items = App\Alumno::all();
    	$pdf = PDF::loadView('reportepdf.alumnopdf', ['items' => $items]);
    	return $pdf->stream('alumnos.pdf');
    });
    Route::get('profesorespdf', function(){
    	$items = App\Profesor::all();
    	$pdf = PDF::loadView('reportepdf.profesorpdf', ['items' => $items]);
    	return $pdf->stream('profesores.pdf');
    });
    Route::get('representantespdf', function(){
    	$items = App\Representante::all();
    	$pdf = PDF::loadView('reportepdf.representantepdf', ['items' => $items]);
    	return $pdf->stream('representantes.pdf');
    });
    Route::get('inscripcionespdf', function(){
    	$items = App\Alumno::all();
    	$pdf = PDF::loadView('reportepdf.inscripcionpdf', ['items' => $items]);
    	return $pdf->stream('inscripciones.pdf');
    });

    Route::get('repalumnospdf/{id}/',[
		'uses' => 'alumnosController@reporte',
		 'as'  => 'reportealumnos'
	]);

    Route::post('validarcedula',[
		'uses' => 'representantesController@validar',
		 'as'  => 'validarcedula'
	]);

});

app/Representante.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Representante extends Model
{
    protected $table = 'representantes';
    protected $fillable = [
    	'nombre',
    	'apellidos',
    	'cedula',
    	'telefono',
    	'correo',
    	'direccion',
    ];
   /* public function alumno()
    {
    	return $this->hasMany('App\Alumno');
    }*/

}

app/Http/Controllers/representantesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use \App\Representante;
use \App\User;
use \App\Alumno;

class representantesController extends Controller
{
	public function index()
    {
        $items = Representante::orderBy('cedula', 'asc')->paginate(200);
    	return view('consultar.representante.index', compact('items'));
    }
    public function validar(Request $request){
        $validatedData = $request->validate([
        'cedula' => 'required|unique:representantes|min:1000000|max:99999999|numeric',
         ]);
        return redirect()->route('representante.create', $request->cedula);
    }
    public function create($cedula){
        return view('insertar.representante.create', compact('cedula'));
    }
    public function store(Request $request){
    	Representante::create($request->all());
        $item = Representante::orderBy('created_at', 'desc')->first();
       return redirect('/home');
    }
    public function edit($id){
        $item = Representante::find($id);
        return view('consultar.representante.edit', compact('item'));
    }
    public function update($id, Request $request)
    {
        $item = Representante::find($id);
        $item->fill($request->all());
        $item->save();
        return redirect('/representantes');
    }
  /*  public function edit($id){
    	$item = Representante::find($id);
        return view('admin.representantes.edit', compact('item'));
    
    public function update($id, Request $request){
    	$item = Representante::find($id);
    	$item->fill($request->all());
    	$item->save();
        return redirect('/representante');
    }
    public function show(){
        return "Error de metodo de envio de datos";
    }
    public function destroy($id)
    {
    	$item = Representante::find($id);
    	$item->delete();   
        return back();	
    }
    public function alumnoCreate($id) {
        $item = Representante::find($id);
        return view('admin.representantes.alumnos.create', compact('item'));
    }
    public function verAlumnos($id){
        $items = Alumno::where('id_representante', $id)->orderBy('cedula', 'asc')->paginate(15);
        return view('admin.alumnos.index', compact('items'));
    }*/
}

resources/views/insertar/representante/create.blade.php
@extends('layouts.app')

@section('content')
    <div id="content-header">
    <div id="breadcrumb"> <a href="index.html" title="Go to Home" class="tip-bottom"><i class="icon-home"></i> Insertar </a> <a href="#" class="tip-bottom">Representante</a> <a href="#" class="current"></div>
  </div>


<div class="span10">
 <div class="widget-box">
        <div class="widget-title"> <span class="icon"> <i class="icon-align-justify"></i> </span>
          <h5>Información del Representante con C.I: {{$cedula}}</h5>
        </div>
        <div class="widget-content nopadding">
      
          <form action="{{route('representantes.store')}}" class="form-horizontal" method="post">
            {{ csrf_field() }}
            <input type="hidden" class="span7" placeholder="Cedula" value="{{$cedula}}"  name="cedula" required/>
            <div class="control-group">
              <label class="control-label">Nombres:</label>
              <div class="controls">
                <input type="text" class="span7" placeholder="Nombres"  name="nombre" required />
              </div>
            </div>
            <div class="control-group">
              <label class="control-label">Apellidos:</label>
              <div class="controls">
                <input type="text" class="span7" placeholder="Apellidos"  name="apellidos" required/>
              </div>
            </div>
             <div class="control-group">
              <label class="control-label">Teléfono:</label>
              <div class="controls">
                <input type="number" class="span7" maxlength="11" placeholder="Teléfono"  name="telefono" required/>
              </div>
            </div>
            <div class="control-group">
              <label class="control-label">Correo Electrónico</label>
              <div class="controls">
                <input type="email" class="span7" placeholder="Correo"  name="correo" required/>
              </div>
            </div>
            <div class="control-group">
              <label class="control-label">Dirección:</label>
              <div class="controls">
                <input type="text" class="span7" placeholder="Dirección" name="direccion" required/>
              </div>
            </div>
            <div class="form-actions">
              <button type="submit" class="btn btn-success">Guardar datos del representante</button>
            </div>
          </form>
          </div>
        </div>
</div>


@endsection