routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('login');
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware'=>['admin']], function (){
	Route::get('/consultar', function () {
    return view('consultar');
	});
	Route::get('/insertar', function () {
	    return view('insertar');
	});
	Route::get('/reportes', function () {
	    return view('reportes');
	});
	Route::resource('alumnos', 'alumnosController');
	Route::resource('aula', 'aulaController');
	Route::resource('profesores', 'profesoresController');
	Route::resource('inscripcion', 'inscripcionesController');
	Route::post('nota/store',[
		'uses' => 'notasController@store',
		 'as'  => 'nota.store'
	]);
	Route::get('nota/{id}/consultar',[
		'uses' => 'notasController@consultar',
		 'as'  => 'nota.consultar'
	]);
	Route::get('notas/index',[
		'uses' => 'notasController@index',
		 'as'  => 'notas'
	]);
	Route::resource('notas', 'notasController');
	Route::get('cuentas/create',[
		'uses' => 'HomeController@create',
		 'as'  => 'cuentas.create'
	]);
	Route::post('cuentas/store',[
		'uses' => 'HomeController@store',
		 'as'  => 'cuentas.store'
	]);
	Route::resource('representantes', 'representantesController');
	Route::get('representante/create/{cedula}', [
		'uses'	=> 'representantesController@create',
		'as'	=> 'representante.create'
	]);
	  Route::post('profesores/cedula', [
		'uses'	=> 'profesoresController@cedula',
		'as'	=> 'profesores.cedula'
	]);
	Route::get('alumno/validar/{cedula}', [
		'uses'	=> 'alumnosController@validar',
		'as'	=> 'alumno.validar'
	]);
  Route::get('alumno/getalumno/{id}', [
    'uses'	=> 'alumnosController@getAlumno',
    'as'	=> 'alumno.getAlumno'
  ]);

    Route::get('alumnospdf', function(){
    	$items = App\Alumno::all();
    	$pdf = PDF::loadView('reportepdf.alumnopdf', ['items' => $items]);
    	return $pdf->stream('alumnos.pdf');
    });
    Route::get('profesorespdf', function(){
    	$items = App\Profesor::all();
    	$pdf = PDF::loadView('reportepdf.profesorpdf', ['items' => $items]);
    	return $pdf->stream('profesores.pdf');
    });
    Route::get('representantespdf', function(){
    	$items = App\Representante::all();
    	$pdf = PDF::loadView('reportepdf.representantepdf', ['items' => $items]);
    	return $pdf->stream('representantes.pdf');
    });
    Route::get('inscripcionespdf', function(){
    	$items = App\Alumno::all();
    	$pdf = PDF::loadView('reportepdf.inscripcionpdf', ['items' => $items]);
    	return $pdf->stream('inscripciones.pdf');
    });

    Route::get('repalumnospdf/{id}/',[
		'uses' => 'alumnosController@reporte',
		 'as'  => 'reportealumnos'
	]);

    Route::post('validarcedula',[
		'uses' => 'representantesController@validar',
		 'as'  => 'validarcedula'
	]);

});

resources/views/consultar/inscripcion/edit.blade.php
@extends('layouts.app')

@section('content')
  <div id="breadcrumb"> <a href="index.html" title="Go to Home" class="tip-bottom"><i class="icon-home"></i>Consultar </a> <a href="#" class="tip-bottom">Inscripción - Editar</a> <a href="#" class="current"></div>
  
<div class="span10">
 <div class="widget-box">
        <div class="widget-title"> <span class="icon"> <i class="icon-align-justify"></i> </span>
          <h5>Editar - Información de inscripción</h5>
        </div>
        <div class="widget-content nopadding">
      
          {!!Form::model($item,['route'=>['inscripcion.update', $item->id],'method'=>'PUT','class' => 'form-horizontal', 'files' => true, 'enctype'=>'multipart/form-data'])!!}
            {{ csrf_field() }}
            <div class="control-group">
              <label class="control-label">Nombres:</label>
              <div class="controls">
                <input type="text" class="span7" value="{{$item->nombres}}" c name="nombres" placeholder="Nombres" required/>
              </div>
            </div>
            <div class="control-group">
              <label class="control-label">Apellidos:</label>
              <div class="controls">
                <input type="text" class="span7" name="apellidos" value="{{$item->apellidos}}" placeholder="Apellidos" required />
              </div>
            </div>
            <div class="control-group">
              <label class="control-label">Fecha de Ingreso:</label>
              <div class="controls">
                <input type="date" name="fecha_ing" value="{{$item->fecha_ing}}"  class="span7" required/>
              </div>
            </div>
             <div class="control-group">
              <label class="control-label">Partida de Nacimiento</label>
              <div class="controls">
                <label>
                   {!!Form::radio('partida_nac', 'Si' , true)!!}
                  Si</label>
                   <label>
                  {!!Form::radio('partida_nac', 'No' , true)!!}
                  No</label>
                </div>
              </div>
              <div class="control-group">
              <label class="control-label">Copia de cedula Representante</label>
              <div class="controls">
                <label>
                          {!!Form::radio('cedula_rep', 'Si' , true)!!}
                          Si</label>
                        <label>
                         {!!Form::radio('cedula_rep', 'No' , true)!!}
                          No
                       </label>
              </div>
            <div class="control-group">
              <label class="control-label">Representante</label>
              <div class="controls">
                <select name="id_representante"  >
                  <option selected value="{{$item->id_representante}}">{{$item->representante->cedula}} - {{$item->representante->nombre}}</option>
                     @foreach($repres as $repre)

                             <option value="{{$repre->id}}">{{$repre->cedula}} - {{$repre->nombre}}</option>
                    @endforeach   
                </select>
              </div>
            </div>
             <div class="control-group">
              <label class="control-label">Profesor</label>
              <div class="controls">
                <select name="id_profesor">
                  <option selected value="{{$item->id_profesor}}">{{$item->profesor->cedula}} - {{$item->profesor->nombre}}</option>
                     @foreach($prof as $profs)
                             <option value="{{$profs->id}}">{{$profs->cedula}} - {{$profs->nombre}}</option>
                    @endforeach   
                </select>
                </select>
              </div>
            </div>
            <div class="control-group">
              <label class="control-label">Sección</label>
              <div class="controls">
                <select name="seccion" >
                  <option selected value="{{$item->seccion}}">{{$item->seccion}}</option>
                  <option value="A">A</option>
                  <option value="B">B</option>
                  <option value="C">C</option>
                </select>
              </div>
            </div>
            <div class="control-group">
              <label class="control-label">Aula</label>
              <div class="controls">
                 <select name="aula" >
                  <option selected value="{{$item->aula}}">{{$item->aula}}</option>
                  @for($i=1; $i < 11; $i++)
                      <option value="{{ $i }}">{{ $i }}</option>    
                  @endfor
                </select>

            </div>
            <div class="control-group">
              <label class="control-label">Turno</label>
              <div class="controls">
                <select name="turno" >
                  <option selected value="{{$item->turno}}">{{$item->turno}}</option>
                  <option value="Mañana">Mañana</option>
                  <option value="Tarde">Tarde</option>
                </select>
              </div>
            </div>
            <div class="control-group">
              <label class="control-label">Descripción</label>
              <div class="controls">
                <textarea name="descripcion" class="span7" >{{$item->descripcion}}</textarea>
              </div>
            </div>
            <div class="form-actions">
              <button type="submit" class="btn btn-success">Aceptar</button>
            </div>
          {!!Form::close()!!}
          </div>
        </div>
</div>

@endsection

resources/views/consultar/inscripcion/index.blade.php
@extends('layouts.app')

@section('content')
   <div id="content-header">
    <div id="breadcrumb"> <a href="index.html" title="Go to Home" class="tip-bottom"><i class="icon-home"></i> Consultar</a> <a href="#" class="tip-bottom">Inscripción</a> <a href="#" class="current"></div>
  </div>


<div class="span10">

        <div class="widget-box">
          <div class="widget-title"> <span class="icon"> <i class="icon-th"></i> </span>
            <h5>Consultar Representantes</h5>
          </div>
          <div class="widget-content nopadding">
            <table class="table table-bordered table-striped">
              <thead>
                <tr>
                  <th>ID</th>
                  <th>Nombre Alumno</th>
                  <th>Apellidos Alumno</th>
                  <th>Fecha Ingreso</th>
                  <th>Representante</th>
                  <th>Profesor</th>
                  <th>Aula</th>
                  <th>Sección</th>
                  <th>Turno</th>
                  <th>Opciones</th>
                </tr>
              </thead>
              <tbody>
                 @foreach($items as $item)
                  <tr class="odd gradeX">
                    <td>{{$item->id}}</td>
                    <td>{{$item->nombres}}</td>
                    <td>{{$item->apellidos}}</td>
                    <td>{{$item->fecha_ing}}</td>
                    <td>{{$item->representante->cedula}} {{$item->representante->nombre}} {{$item->representante->apellidos}}</td>
                    <td>{{$item->profesor->cedula}} {{$item->profesor->nombre}} {{$item->profesor->apellidos}}</td>
                    <td>{{$item->aula}}</td>
                    <td>{{$item->seccion}}</td>
                    <td>{{$item->turno}}</td>
                    <td >  <center> <a href="{{route('inscripcion.edit', $item->id)}}" class="btn btn-mini btn-warning">Modificar</a> <a href="{{url('repalumnospdf', $item->id)}}" class="btn btn-mini btn-primary">PDF</a></center></td>
                  </tr>
                 @endforeach
              </tbody>
            </table>
          </div>
        </div>
        
</div>



<!--Footer-part-->

<div class="row-fluid">
  <div id="footer" class="span12"> 2018 &copy; Unidad Educativa Simoncito "Las Americas" <a href="http://themedesigner.in"> - Desarrollado por: Francisco La Rosa</a> </div>
</div>
@endsection